doctrine_migrations:
  migrations_paths:
    'App\Infrastructure\Migrations': '%kernel.project_dir%/src/Infrastructure/Migrations'
  storage:
    table_storage:
      table_name: 'doctrine_migration_versions'
      version_column_name: 'version'
      executed_at_column_name: 'executed_at'
      execution_time_column_name: 'execution_time'

